[package]
name = "server"
version = "0.2.0"
description = "An express-like server for Motoko"
repository = "https://github.com/krpeacock/server"

[dependencies]
certified-cache = "0.2.0"
json = "https://github.com/aviate-labs/json.mo#main"
array = "https://github.com/aviate-labs/array.mo#main"
encoding = "https://github.com/aviate-labs/encoding.mo#main"
motoko-sha = "https://github.com/enzoh/motoko-sha#master"
serde = "0.2.0"
test = "1.0.1"
base = "0.8.7"
assets = "0.2.0"
"http-parser.mo" = "https://github.com/NatLabs/http-parser.mo#v0.1.2"
