[package]
name = "server"
version = "2.0.0"
description = "An express-like server for Motoko"
repository = "https://github.com/krpeacock/server"
keywords = [
  "motoko",
  "server",
  "express",
  "http",
  "certified",
  "cache",
  "assets"
]
license = "Apache-2.0"

[dependencies]
certified-cache = "0.3.0"
test = "2.0.0"
base = "0.12.1"
assets = "0.2.2"
http-parser = "0.3.1"
serde = "3.1.0"
